#!/bin/bash

ADDED_BY_LINE="# Added by $0"

echo


if ! [[ -f "$HOME/.tmux.conf" ]]; then
    echo "Creating a \"$HOME/.tmux.conf\" file."
fi
if grep "^${ADDED_BY_LINE}\$" "$HOME/.tmux.conf" >&/dev/null; then
    echo "------------------  Found \"${ADDED_BY_LINE}\" in \"$HOME/.tmux.conf\"."
else
    echo "Appending stuff to \"$HOME/.tmux.conf\""
    echo >> "$HOME/.tmux.conf"
    echo "${ADDED_BY_LINE}" >> "$HOME/.tmux.conf"
    echo "bind-key Space next-window" >> "$HOME/.tmux.conf"
    echo "set -s escape-time 0" >> "$HOME/.tmux.conf"
    echo "set-option -g renumber-windows on" >> "$HOME/.tmux.conf"
fi


echo


if ! [[ -f "$HOME/.inputrc" ]]; then
    echo "Creating a \"$HOME/.inputrc\" file."
fi
if grep "^[\$]include $HOME/profile/inputrc_common\$" "$HOME/.inputrc" >&/dev/null; then
    echo "------------------  Found \"$HOME/profile/inputrc_common\" in \"$HOME/.inputrc\"."
else
    echo "Appending \"\$include $HOME/profile/inputrc_common\" to \"$HOME/.inputrc\""
    echo >> "$HOME/.inputrc"
    echo "${ADDED_BY_LINE}" >> "$HOME/.inputrc"
    echo "\$include $HOME/profile/inputrc_common" >> "$HOME/.inputrc"
fi


echo


if ! [[ -f "$HOME/.bashrc" ]]; then
    echo "Creating a \"$HOME/.bashrc\" file."
fi
if grep "^[.] \"$HOME/profile/bashrc_common\"\$" "$HOME/.bashrc" >&/dev/null; then
    echo "------------------  Found \"$HOME/profile/bashrc_common\" in \"$HOME/.bashrc\"."
else
    echo "Appending \". $HOME/profile/bashrc_common\" to \"$HOME/.bashrc\""
    echo >> "$HOME/.bashrc"
    echo "${ADDED_BY_LINE}" >> "$HOME/.bashrc"
    echo ". \"$HOME/profile/bashrc_common\"" >> "$HOME/.bashrc"
fi


echo


if ! [[ -f "$HOME/.vimrc" ]]; then
    echo "Creating a \"$HOME/.vimrc\" file."
fi
if grep "^source $HOME/profile/vimrc_common\$" "$HOME/.vimrc" >&/dev/null; then
    echo "------------------  Found \"$HOME/profile/vimc_common\" in \"$HOME/.vimrc\"."
else
    echo "Appending \"source $HOME/profile/vimrc_common\" to \"$HOME/.vimrc\""
    echo >> "$HOME/.vimrc"
    echo "${ADDED_BY_LINE}" >> "$HOME/.vimrc"
    echo "source $HOME/profile/vimrc_common" >> "$HOME/.vimrc"
fi


echo


if [[ -d "$HOME/bin" ]]; then
    echo "------------------  Found \"$HOME/bin\"."
else
    echo "Creating \"$HOME/bin\"."
    mkdir "$HOME/bin"
fi

echo

if [[ -d "$HOME/bin/src" ]]; then
    echo "------------------  Found \"$HOME/bin/src\"."
else
    echo "Creating \"$HOME/bin/src\"."
    mkdir "$HOME/bin/src"
fi


echo



PROG="icdiff"
GH_PROG_URL='https://github.com/jeffkaufman/icdiff'

if [[ -e "$HOME/bin/$PROG" ]]; then
    echo "------------------  Found \"$HOME/bin/$PROG\"."
else
    echo "Calling \"git clone $GH_PROG_URL\"."
    pushd "$HOME/bin/src"
    git clone $GH_PROG_URL
    cd ..
    ln -s "src/$PROG/$PROG"
    popd
fi


echo


PROG="cv"
GH_PROG_URL='https://github.com/Xfennec/cv'

if [[ -e "$HOME/bin/$PROG" || -L "$HOME/bin/$PROG" ]]; then
    echo "------------------  Found \"$HOME/bin/$PROG\"."
else
    echo "Calling \"git clone $GH_PROG_URL\"."
    pushd "$HOME/bin/src"
    git clone $GH_PROG_URL
    cd "$PROG"
    make
    cd ..
    cd ..
    ln -s "src/$PROG/$PROG"
    popd
fi


echo


if [[ -r "$HOME/.vim/autoload/plug.vim" ]]; then
    echo "------------------  Found \"$HOME/.vim/autoload/plug.vim\"."
else
    if which curl; then
        curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    elif which wget; then
        mkdir -p "$HOME/.vim/autoload"
        wget -O "$HOME/.vim/autoload/plug.vim" \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    else
        echo -n "Please run: `wget -O \"$HOME/.vim/autoload/plug.vim\" "
        echo -n "https://raw.githubusercontent.com/junegunn/vim-plug/master/"
        echo "plug.vim`.  And then hit ENTER."
        read a
    fi
    # No idea if this'll work, generally.
    vim -c ':PlugInstall|q!|q!'
fi


echo


echo
echo "------------------  Done."
echo
